"""create payment tables

Revision ID: 7ffec9af2906
Revises: 
Create Date: 2026-10-01 00:03:52.142821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ffec9af2906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_projections',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_cents', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'scheduled', 'partially_paid', 'paid', 'void')", name='ck_projection_invoice_status'),
    sa.CheckConstraint('total_cents >= 0 AND amount_paid_cents >= 0 AND amount_paid_cents <= total_cents', name='ck_projection_not_overpaid'),
    sa.PrimaryKeyConstraint('invoice_id'),
    schema='payment'
    )
    op.create_index('ix_projection_status_due_date', 'invoice_projections', ['status', 'due_date'], unique=False, schema='payment')
    op.create_table('payment_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('created', 'executing', 'completed', 'completed_with_errors', 'needs_reconciliation')", name='ck_payment_run_status'),
    sa.CheckConstraint('total_cents >= 0', name='ck_payment_run_total_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    schema='payment'
    )
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    schema='payment'
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_reference', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'in_flight', 'succeeded', 'failed', 'unknown')", name='ck_payment_status'),
    sa.CheckConstraint('amount_cents > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['payment.invoice_projections.invoice_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['payment.payment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('run_id', 'invoice_id', name='uq_payment_run_invoice'),
    schema='payment'
    )
    op.create_index('uq_payment_active_invoice', 'payments', ['invoice_id'], unique=True, schema='payment', postgresql_where=sa.text("status IN ('queued', 'in_flight', 'unknown')"))
   
    
   
 
    
   

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
   
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='invoice'
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('outbox_events_pkey')),
    schema='invoice'
    )
    op.create_index(op.f('ix_outbox_unpublished'), 'outbox_events', ['published_at', 'created_at'], unique=False, schema='invoice')
    op.create_table('invoice_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price_cents', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('line_total_cents', sa.BIGINT(), sa.Computed('(quantity * unit_price_cents)', persisted=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_invoice_line_quantity_positive')),
    sa.CheckConstraint('unit_price_cents >= 0', name=op.f('ck_invoice_line_price_nonnegative')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoices.id'], name=op.f('invoice_lines_invoice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_lines_pkey')),
    schema='invoice'
    )
    op.drop_index('uq_payment_active_invoice', table_name='payments', schema='payment', postgresql_where=sa.text("status IN ('queued', 'in_flight', 'unknown')"))
    op.drop_table('payments', schema='payment')
    op.drop_table('processed_events', schema='payment')
    op.drop_table('payment_runs', schema='payment')
    op.drop_index('ix_projection_status_due_date', table_name='invoice_projections', schema='payment')
    op.drop_table('invoice_projections', schema='payment')
    # ### end Alembic commands ###
