"""add payment outbox

Revision ID: 8622dcdb44dc
Revises: 7ffec9af2906
Create Date: 2026-10-07 15:14:08.678828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8622dcdb44dc'
down_revision: Union[str, Sequence[str], None] = '7ffec9af2906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='payment'
    )
    op.create_index('ix_payment_outbox_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False, schema='payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_outbox_unpublished', table_name='outbox_events', schema='payment')
    op.drop_table('outbox_events', schema='payment')
    # ### end Alembic commands ###
