server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location /vendors {
        proxy_pass http://invoice-api:8001;
    }

    location /invoices {
        proxy_pass http://invoice-api:8001;
    }

    location /payment-runs {
        proxy_pass http://payment-api:8002;
    }

    location /reports {
        proxy_pass http://payment-api:8002;
    }

    location / {
        try_files $uri /index.html;
    }
}