"""create invoice schema

Revision ID: 9f1af8713f8b
Revises: 
Create Date: 2026-09-30 00:06:01.434367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1af8713f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='invoice'
    )
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False, schema='invoice')
    op.create_table('vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='invoice'
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'scheduled', 'partially_paid', 'paid', 'void')", name='ck_invoice_status'),
    sa.CheckConstraint('amount_paid_cents >= 0 AND amount_paid_cents <= total_cents', name='ck_invoice_not_overpaid'),
    sa.CheckConstraint('total_cents >= 0', name='ck_invoice_total_nonnegative'),
    sa.ForeignKeyConstraint(['vendor_id'], ['invoice.vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'invoice_number', name='uq_invoice_vendor_number'),
    schema='invoice'
    )
    op.create_index('ix_invoice_status_due_date', 'invoices', ['status', 'due_date'], unique=False, schema='invoice')
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('line_total_cents', sa.BigInteger(), sa.Computed('quantity * unit_price_cents', persisted=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_line_quantity_positive'),
    sa.CheckConstraint('unit_price_cents >= 0', name='ck_invoice_line_price_nonnegative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='invoice'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_lines', schema='invoice')
    op.drop_index('ix_invoice_status_due_date', table_name='invoices', schema='invoice')
    op.drop_table('invoices', schema='invoice')
    op.drop_table('vendors', schema='invoice')
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events', schema='invoice')
    op.drop_table('outbox_events', schema='invoice')
    # ### end Alembic commands ###
